ALTER TABLE cycles ADD COLUMN vision TEXT NOT NULL DEFAULT '';
ALTER TABLE cycles ADD COLUMN success_definition TEXT NOT NULL DEFAULT '';
ALTER TABLE cycles ADD COLUMN why_it_matters TEXT NOT NULL DEFAULT '';
ALTER TABLE cycles ADD COLUMN blockers TEXT NOT NULL DEFAULT '';
ALTER TABLE cycles ADD COLUMN risks TEXT NOT NULL DEFAULT '';
ALTER TABLE cycles ADD COLUMN lag_measures TEXT NOT NULL DEFAULT '';
ALTER TABLE cycles ADD COLUMN lead_measures TEXT NOT NULL DEFAULT '';
ALTER TABLE cycles ADD COLUMN notes TEXT NOT NULL DEFAULT '';
